// src/App.tsx
import Component from "vue-class-component";
import BaseComponent from "./components/BaseComponent";
import BaseApp from "./components/App";
import AppLayout from "./AppLayout";

@Component({
  name: "App",
})
class App extends BaseComponent<{}> {
  route = location.pathname;

  changeRoute(route: string) {
    history.pushState(null, "Title", route);
    this.route = route;
  }

  render() {
    return (
      <BaseApp
        defaultLocale="de_DE"
        currentPath={this.route}
        devMode
        handleRouteChange={console.log}
        components={{
          appLayout: AppLayout,
        }}
      />
    );
    /**return (
      <Page
        currentPath={this.route}
        devMode
        defaultLocale="en_GB"
        locales={["de_DE", "en_GB"]}
        handleRouteChange={route => {
          if (route) this.changeRoute(route);
        }}
      />
    );**/
  }
}
export default App;

// src/App.vue
<template>
  <fsxa-app
    defaultLocale="de_DE"
    devMode="true"
    :handleRouteChange="handleRouteChange"
    :currentPath="route"
    :components="components"
  />
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import AppLayout from "./AppLayout.vue";
import FSXAApp from "./components/App";

Vue.component("app-layout", AppLayout);

@Component({
  name: "VueFSXAApp",
  components: {
    "fsxa-app": FSXAApp,
    layout: AppLayout,
  },
})
class App extends Vue {
  route = location.pathname;

  get components() {
    return {
      appLayout: AppLayout,
    };
  }

  handleRouteChange() {
    console.log("Route changed");
  }
}
export default App;
</script>
